# Code quality checks
name: Code Quality

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    name: Code Quality Checks
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Check file sizes
        run: |
          echo "Checking file sizes..."
          find src -name "*.js" -size +100k -exec echo "❌ File too large: {}" \; -exec exit 1 \;
          echo "✅ All files within size limits"
      
      - name: Security check - no sensitive data
        run: |
          echo "Checking for sensitive data..."
          # Check for API keys
          if grep -r "api[_-]key\|apikey" src/ --exclude-dir=node_modules -i; then
            echo "❌ Potential API key found"
            exit 1
          fi
          # Check for passwords
          if grep -r "password\|pwd\|passwd" src/ --exclude-dir=node_modules -i; then
            echo "❌ Potential password found"
            exit 1
          fi
          echo "✅ No sensitive data found"
      
      - name: Check CSS line count
        run: |
          for file in src/content/css/*.js; do
            lines=$(wc -l < "$file")
            if [ $lines -gt 600 ]; then
              echo "❌ CSS file too large: $file ($lines lines)"
              exit 1
            fi
          done
          echo "✅ CSS files within limits"