# Test workflow - runs on all PRs
name: PR Validation

on:
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Validate PR
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check file structure
        run: |
          echo "Checking critical files exist..."
          test -f src/index.js || exit 1
          test -f wrangler.toml || exit 1
          test -f package.json || exit 1
          echo "✅ All critical files present"
      
      - name: Validate JSON files
        run: |
          echo "Validating JSON files..."
          node -e "JSON.parse(require('fs').readFileSync('package.json'))"
          node -e "JSON.parse(require('fs').readFileSync('manifest-ar.json'))"
          node -e "JSON.parse(require('fs').readFileSync('manifest-en.json'))"
          echo "✅ All JSON files valid"
      
      - name: Check for console.error
        run: |
          if grep -r "console\.error" src/ --exclude-dir=node_modules; then
            echo "❌ Found console.error statements"
            exit 1
          fi
          echo "✅ No console.error found"
      
      - name: Validate Worker syntax
        run: |
          node -c src/index.js
          echo "✅ Worker syntax valid"